openapi: 3.0.0
info:
  title: Service API
  version: 1.0.0

paths:
  /reservations:
    post:
      summary: Create a reservation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationDTO'
      responses:
        '201':
          description: Reservation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationDTO'

components:
  schemas:
    ReservationDTO:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        carId:
          type: integer
        fromDate:
          type: string
          format: date
        toDate:
          type: string
          format: date
