openapi: 3.0.0
info:
  title: Service API
  version: 1.0.0

paths:
  /cars:
    post:
      summary: Add a new car
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarDTO'
      responses:
        '201':
          description: Car added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarDTO'


components:
  schemas:
   
    CarDTO:
      type: object
      properties:
        id:
          type: integer
        make:
          type: string
        model:
          type: string
        year:
          type: integer

  